-- MySQL Script generated by MySQL Workbench
-- Fri 28 Jul 2017 03:44:05 AM AMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itriad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `itriad` ;

-- -----------------------------------------------------
-- Schema itriad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itriad` DEFAULT CHARACTER SET utf8 ;
USE `itriad` ;

-- -----------------------------------------------------
-- Table `itriad`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itriad`.`produto` ;

CREATE TABLE IF NOT EXISTS `itriad`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `custo_transporte` DECIMAL(10,2) NOT NULL,
  `max_item_palete` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itriad`.`transportadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itriad`.`transportadora` ;

CREATE TABLE IF NOT EXISTS `itriad`.`transportadora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itriad`.`transportadora_custo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itriad`.`transportadora_custo` ;

CREATE TABLE IF NOT EXISTS `itriad`.`transportadora_custo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `custo_ar` DECIMAL(10,2) NOT NULL,
  `custo_terra` DECIMAL(10,2) NOT NULL,
  `custo_agua` DECIMAL(10,2) NOT NULL,
  `custo_palete` DECIMAL(10,2) NOT NULL,
  `custo_quilo` DECIMAL(10,2) NOT NULL,
  `transportadora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transportadora_custo_transportadora_idx` (`transportadora_id` ASC),
  UNIQUE INDEX `transportadora_id_UNIQUE` (`transportadora_id` ASC),
  CONSTRAINT `fk_transportadora_custo_transportadora`
    FOREIGN KEY (`transportadora_id`)
    REFERENCES `itriad`.`transportadora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `itriad`.`produto`
-- -----------------------------------------------------
START TRANSACTION;
USE `itriad`;
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (1, 'Samsung Galaxy S', 'S0001', 'Prata', 145, 800, 2.5, 100);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (2, 'Samsung Galaxy S2', 'S0002', 'Preto', 147, 900, 3, 110);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (3, 'Samsung Galaxy S3', 'S0003', 'Verde', 149, 1000, 3.5, 120);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (4, 'Samsung Galaxy S4', 'S0004', 'Azul', 151, 1100, 4, 130);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (5, 'Samsung Galaxy S5', 'S0005', 'Branco', 153, 1200, 4.5, 140);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (6, 'Samsung Galaxy S6', 'S0006', 'Dourado', 155, 1300, 5, 150);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (7, 'Samsung Galaxy S7', 'S0007', 'Vermelho', 157, 1400, 5.5, 160);
INSERT INTO `itriad`.`produto` (`id`, `descricao`, `modelo`, `cor`, `peso`, `preco`, `custo_transporte`, `max_item_palete`) VALUES (8, 'Samsung Galaxy S8', 'S0008', 'Rosa', 159, 1500, 6, 170);

COMMIT;


-- -----------------------------------------------------
-- Data for table `itriad`.`transportadora`
-- -----------------------------------------------------
START TRANSACTION;
USE `itriad`;
INSERT INTO `itriad`.`transportadora` (`id`, `nome`, `cidade`) VALUES (DEFAULT, 'Sedex', 'Manaus');
INSERT INTO `itriad`.`transportadora` (`id`, `nome`, `cidade`) VALUES (DEFAULT, 'FedEx', 'Manaus');
INSERT INTO `itriad`.`transportadora` (`id`, `nome`, `cidade`) VALUES (DEFAULT, 'PAC', 'Manaus');

COMMIT;


-- -----------------------------------------------------
-- Data for table `itriad`.`transportadora_custo`
-- -----------------------------------------------------
START TRANSACTION;
USE `itriad`;
INSERT INTO `itriad`.`transportadora_custo` (`id`, `custo_ar`, `custo_terra`, `custo_agua`, `custo_palete`, `custo_quilo`, `transportadora_id`) VALUES (1, 9.5, 3.5, 2.5, 300, 4.5, 1);
INSERT INTO `itriad`.`transportadora_custo` (`id`, `custo_ar`, `custo_terra`, `custo_agua`, `custo_palete`, `custo_quilo`, `transportadora_id`) VALUES (2, 8.5, 2.5, 2.0, 200, 3.5, 2);
INSERT INTO `itriad`.`transportadora_custo` (`id`, `custo_ar`, `custo_terra`, `custo_agua`, `custo_palete`, `custo_quilo`, `transportadora_id`) VALUES (3, 7.5, 1.5, 1.5, 100, 2.5, 3);

COMMIT;

